# Generated by Django 4.0.2 on 2022-02-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_laboral', models.CharField(choices=[('P', 'Produccion'), ('C', 'Calidad'), ('R', 'RRHH'), ('A', 'Administracion'), ('E', 'Expedicion'), ('T', 'Tecnica'), ('x', 'Postulante')], max_length=1)),
                ('puesto_laboral', models.CharField(max_length=30)),
                ('descrpcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fec_nac', models.DateField(verbose_name='fecha nacimiento')),
                ('fec_ing', models.DateField(blank=True, verbose_name='fecha ingreso')),
                ('activo', models.BooleanField(default=False, verbose_name='Empleado activo?')),
                ('puesto', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_RRHH.puestolaboral')),
            ],
        ),
    ]
