# Generated by Django 4.0.2 on 2022-02-22 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_RRHH.puestolaboral'),
        ),
    ]
